name: Test

on:
  workflow_dispatch:
    inputs:
      server:
        default: ServerName
        type: string
        required: false
      source:
        default: "Test\\Test1"
        required: true

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: copy
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "${{ github.events.inputs.source }} 
        
        
        
    
      
